### ISSUE TITLE
Unable to get access token

### ISSUE THREAD

**Issue by HemendraGangwar** [0x13a/tinder-api#1]
On Response i am getting the 401 access denied error.

Response : {"meta":{"status":401},"error":{"code":40110}}

Can you please tell why i am getting this error,while i am sending the right facebook token?

**Comment by 0x13a** [comment]
once you approve the tinder app on facebook, you should get a response payload, where you have your facebook token for tinder. It's a ~200 char string token

**Comment by HemendraGangwar** [comment]
I am login with facebook a getting access token there for the which is already registered with Tinder but still i am getting same error.Please Help.I took my the whole day for solving this error but still at same stage :(

**Comment by 0x13a** [comment]
well this is not an issue related with the library itself

**Comment by HemendraGangwar** [comment]
Yes i know that but i need help so just commented

**Comment by h2hjastermereel** [comment]
Same error here, did you ever get past this HemendraGangwar ??

**Comment by 0x13a** [comment]
@h2hjastermereel @HemendraGangwar https://www.facebook.com/v2.6/dialog/oauth?redirect_uri=fb464891386855067%3A%2F%2Fauthorize%2F&scope=user_birthday,user_photos,user_education_history,email,user_relationship_details,user_friends,user_work_history,user_likes&response_type=token%2Csigned_request&client_id=464891386855067 Go to this link. Once you approved the tinder app, open the network tab in the browser and search for the POST https://www.facebook.com/v2.6/dialog/oauth/confirm?dpr=2 call. 

From there you have to copy the response, which is a json. From there search for `access_token`
